### PR TITLE
MAX-17959: Add new Job icon for Service Board

### PR DESCRIPTION
**Pull request by leslieli**

### CODE REVIEW

**Comment by leslieli** [comment]
@elvinfucom @benjaminliugang @dargonwanglong @mallik-svmx @joshsylvester Could you please help review? Thanks.

**Comment by leslieli** [comment]
@mallik-svmx @joshsylvester could you help merge and publish a new tag? Thanks.

**Comment by mallik-svmx** [comment]
@leslieli PR is reviewed, merged and published with release tag v2.2.11. Also, note that you have been added as `admin` to this repo, and you should be able to merge and publish PRs going forward. Thank you and let us know if anything.

**Comment by leslieli** [comment]
OK, thanks @mallik-svmx .

**Comment by leslieli** [comment]
@mallik-svmx  I saw that the tag was published as "2.2.11", not "v2.2.11". Is it expected?

**Comment by mallik-svmx** [comment]
@leslieli My bad. Probably that was the reason why it was still in draft, I have updated it, please let me know if anything. Thanks!

Screen Shot 2020-04-02 at 8 00 36 PM

**Comment by leslieli** [comment]
Thanks @mallik-svmx .

BTW, could you please help to introduce what we need to do and what need to pay attention on when publish a new version? Create a new tag and a new release? Then we can do it by ourself in future.

**Comment by mallik-svmx** [comment]
> Thanks @mallik-svmx .
> 
> BTW, could you please help to introduce what we need to do and what need to pay attention on when publish a new version? Create a new tag and a new release? Then we can do it by ourself in future.

Here are those simple steps:
1. Submit a pull request(as-is today: updates to package.json, bower.json, History.md and feature files).
2. Review and get it approved.
3. Merge the PR.
4. Create darft release notes(under the releases tab)
5. Hit that `Publish release` button when ready.

I hope that helps! Thanks!

Screen Shot 2020-04-03 at 10 04 15 AM

**Comment by leslieli** [comment]
@mallik-svmx Thanks so much, it is helpful.

**Pull request merged**
