### PR TITLE
UI-3151: Updating crew/resource icons using on px-map pins

### PR DESCRIPTION
**Pull request by mallik-svmx**
- Added new customizable icons: `crew` and `resource`
- Added examples changing the backgroundColor
- Use following syntax to render the new icons
`        <px-icon icon="px-svmx:crew"></px-icon>
        <px-icon icon="px-svmx:resource"></px-icon>`

### CODE REVIEW

**Comment by mallik-svmx** [comment]
@nathan03597 @joshsylvester @sheela-svmx @inothings - Can you please review the PR. Thanks!

**Comment by shao** [comment]
China team is on Chinese New Year holidays this week.

@shinxi  @vincentcn @elvinfucom

**Comment by mallik-svmx** [comment]
> China team is on Chinese New Year holidays this week.
> 
> @shinxi @vincentcn @elvinfucom

Thank you for letting us know @shao

**Comment by leslieli** [comment]
@mallik-svmx 

Looks like we are using the wrong image name for Crew/Resource.

Below one should for Crew:
https://github.com/ServiceMax-Engineering/px-icon-set/blob/master/icons/src-svmx/resource.svg

And below one should for Resource:
https://github.com/ServiceMax-Engineering/px-icon-set/blob/master/icons/src-svmx/crew.svg

**Comment by mallik-svmx** [comment]
> https://github.com/ServiceMax-Engineering/px-icon-set/blob/master/icons/src-svmx/crew.svg

@leslieli - Thanks for noticing, I will have it swapped.

**Pull request merged**
