### PR TITLE
MAX-13235 Update icons for Service Board navigation bar

### PR DESCRIPTION
**Pull request by leslieli**
Add new icons in px-smx:
image

### CODE REVIEW

**Comment by leslieli** [comment]
@mallik-svmx @sheela-svmx @joshsylvester @nathan03597 please help review. Thanks.

**Comment by leslieli** [comment]
@mallik-svmx @sheela-svmx could you please help merge and publish a new version? Thanks.

**Comment by mallik-svmx** [comment]
merging with two approvals.

**Comment by mallik-svmx** [comment]
> @mallik-svmx @sheela-svmx could you please help merge and publish a new version? Thanks.

@leslieli PR is merged and published with release tag v2.2.8

**Comment by leslieli** [comment]
Thanks @mallik-svmx

**Pull request merged**
