### PR TITLE
MAX-8963: Add new icons for Service Board

### PR DESCRIPTION
**Pull request by leslieli**
Added px-smx:jobs, px-smx:routes, px-smx:satellite and px-smx:traffic icons for service board.

### CODE REVIEW

**Comment by leslieli** [comment]
@mallik-svmx @elvinfucom @benjaminliugang @joshsylvester @sheela-svmx could you please help review? Thanks.

**Comment by leslieli** [comment]
@mallik-svmx @joshsylvester could you help review and merge? We do not have the permission to merge. Also please help to publish a new tag after merging. Thanks.

**Comment by mallik-svmx** [comment]
@leslieli PR reviewed, merged and published tag v2.2.10. Please let us know if anything. Thank you!

**Comment by leslieli** [comment]
Thanks @mallik-svmx

**Comment by leslieli** [comment]
@mallik-svmx I saw that the tag was published as "2.2.11", not "v2.2.11". Is it expected?

**Pull request merged**
